version: '3.7'

services:
  db:
    container_name: test_postgres
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/pgsql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: test_adminer
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080


volumes:
  pgdata:
