version: '3.7'

services:
  web:
    container_name: test_web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - env/.dev.env
    command:
      python main.py
    depends_on:
      - db

  db:
    container_name: test_postgres
    image: postgres:14.2
    restart: always
    env_file:
      - env/.dev.env
    volumes:
      - pgdata:/var/lib/pgsql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: test_adminer
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080


volumes:
  pgdata:
