name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v1

      - name: Use pipfile
        run: python -m pipenv install --system

      - name: Testing
        run: python -m unittest tests.usecases_tests -bv