name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v1

      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Use pipfile
        run: |
          pip install --user pipenv
          echo "pipenv installed"
          python -m pipenv install Pipfile.lock --system

      - name: Testing
        run: python -m unittest tests.usecases_tests -bv